# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
php:
  - 5.3
  - 5.4
# omitting "script:" will default to phpunit
before_script:
  - composer install
script: phpunit --coverage-text --configuration phpunit.xml
notifications:
  email:
    - ronan.guilloux@gmail.com
